name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-
    
    - name: Build with Maven
      run: |
        mvn -B clean verify -DskipTests
        mvn -B test -Dtest=!BarrierOptionTest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Run failing tests separately
      run: |
        echo "Running failing tests separately..."
        mvn -B test -Dtest=BarrierOptionTest
      if: always()
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          **/surefire-reports/*
          **/failsafe-reports/*
        retention-days: 7
    
    - name: Upload JAR artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: derivatives-pricing-app
        path: target/*.jar
        retention-days: 7
    
    - name: Show Maven version
      run: mvn -v
    
    - name: List files
      run: ls -la
    
    - name: List target directory
      run: ls -la target/ || echo "Target directory not found"
      if: always()
